import = ["/Users/eeken/.config/alacritty/gruvbox-dark.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = false

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Geist Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Geist Mono"
style = "Italic"

[font.normal]
family = "Geist Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u0002c"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002v"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002s"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u0013"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002x"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 240
lines = 60

[window.padding]
x = 2
y = 2
