"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
# truncate_to_repo = false
truncation_length = 4
style = "cyan"

[git_branch]
symbol = ""
style = "green"
format = '[$symbol$branch]($style)'

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "yellow"
modified = "!${count}"
staged = "+${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "!${count}"
renamed = ""
deleted = ""
conflicted = ""
stashed = ""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"
