"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$character"""

right_format = """
$python"""

[username]
style_user = 'yellow'
style_root = 'black bold'
format = '\([$user]($style)@'
disabled = false
show_always = true

[hostname]
ssh_symbol = ''
ssh_only = false
format = '[$hostname]($style)\) '
style = 'yellow'

[directory]
truncate_to_repo = false
truncation_length = 1
home_symbol = "~"
fish_style_pwd_dir_length = 1
style = "cyan"

[git_branch]
symbol = ""
style = "green"
format = '[$symbol$branch]($style)'

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "yellow"
modified = "!${count}"
staged = "+${count}"
ahead = "‚á°${count}"
behind = "‚á£${count}"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
untracked = "?${count}"
renamed = ""
deleted = ""
conflicted = "="
stashed = '\$'

[character]
success_symbol = "[‚ùØ](green)"
error_symbol = "[‚ùØ](red)"
vimcmd_symbol = "[‚ùÆ](purple)"

[python]
format = '[${symbol}(${version} )(\($virtualenv\))]($style)'
symbol = 'üêç '
style = "yellow"
python_binary = ["python3", "python"]
